CREATE TABLE product(
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL,
    type CHAR(1) NOT NULL COMMENT 'PRODUCT_TYPE_*，商品类型',
    name VARCHAR(20) NOT NULL COMMENT '名称',
    additional TEXT DEFAULT NULL COMMENT '描述，JSON',
    update_time DATETIME DEFAULT NOW() NOT NULL COMMENT '更新时间',
    create_time DATETIME DEFAULT NOW() NOT NULL COMMENT '创建时间'
);

ALTER TABLE product ADD INDEX(type);
