CREATE TABLE `user` (
    `id` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `username` VARCHAR(320) NOT NULL,
    `password` VARCHAR(64) NOT NULL,
    `update_at` DATETIME NOT NULL DEFAULT NOW(),
    `create_at` DATETIME NOT NULL DEFAULT NOW()
) DEFAULT CHARSET=utf8mb4;
ALTER TABLE `user` ADD UNIQUE(`username`);
