name: Release
on:
  push:
    branches:
      - 'releases/*'
jobs:
  release:
    name: 'Realese server'
    runs-on: ubuntu-16.04
    steps:
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: '1.13'
      #- name: Setup node
      #  uses: actions/setup-node@v1
      #  with:
      #    node-version: '10.15.0'
      - name: Checkout
        uses: actions/checkout@master
      - name: Build
        run: |
          make install && make release
          tree .
          pwd
      - name: Docker build and push
        run: |
          export VERSION=`echo ${GITHUB_REF}|awk -F '/' '{print $NF}'`
          export IMAGE_NAME=mapleque/cell:${VERSION}
          echo ${IMAGE_NAME}
          tree .
          pwd
          docker login -u mapleque -p ${{ secrets.DOCKER_TOKEN }}
          docker build -t ${IMAGE_NAME} main
          docker push ${IMAGE_NAME}
          docker tag ${IMAGE_NAME} mapleque/cell:latest
          docker push mapleque/cell:latest
      - name: Github Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            releases/cell-mac.zip
            releases/cell-linux.zip
            releases/cell-win64.zip
            releases/cell-win32.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

