name: Release
on:
  push:
    branches:
      - 'releases/*'
jobs:
  release:
    name: 'Realese server'
    runs-on: ubuntu-16.04
    steps:
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: '1.13'
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '10.15.0'
      - name: Checkout
        uses: actions/checkout@master
      - name: Build
        run: make install && make release
      - name: Setup Docker
        uses: actions/docker@master
        env:
          IMAGE_NAME: cell:${GITHUB_REF}
      - name: Docker build and push
        run: docker login -u mapleque -p ${{ secret.DOCKER_TOKEN }} \
              && docker build -t ${IMAGE_NAME} main \
              && docker push ${IMAGE_NAME}
      - name: Github Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            releases/cell-mac.zip
            releases/cell-linux.zip
            releases/cell-win64.zip
            releases/cell-win32.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

