name: Test
on: push

jobs:
  test-go-server:
    name: 'Test go server'
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: '1.13'
      - uses: actions/checkout@master
        run: make test-server

  test-html-client:
    name: 'Test html client'
    runs-on: ubuntu-16.04
      - uses: actions/setup-node@v1
        with:
          node-version: '10.15.0'
      - uses: actions/checkout@master
        run: make test-html-client
